/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import config.dbconn;
import config.session;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class paybills extends javax.swing.JFrame {
    private int billTypeId;
    private String billTypeName;

    /**
     * Creates new form paybills
     */
    public paybills() {
        
        initComponents();
    }  
   public paybills(int billTypeId, String billTypeName) {
        initComponents();
        this.billTypeId = billTypeId;
        this.billTypeName = billTypeName;

        // Display them if needed
        bill_id.setText(String.valueOf(billTypeId));
        billtype.setText(billTypeName);
    }
    Color orange = new Color(255,204,102);
    Color lightorange = new Color(245,216,127);
    Color white = new Color(255,255,255);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        backg3 = new javax.swing.JPanel();
        pay = new javax.swing.JButton();
        cancelbtm = new javax.swing.JButton();
        bill_id = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        title2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        passtxt = new javax.swing.JLabel();
        Fname1 = new javax.swing.JLabel();
        passtxt1 = new javax.swing.JLabel();
        billtype = new javax.swing.JTextField();
        passtxt2 = new javax.swing.JLabel();
        billingperiod = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backg3.setBackground(new java.awt.Color(255, 102, 0));
        backg3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pay.setBackground(new java.awt.Color(255, 255, 255));
        pay.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pay.setText("PAYBILL");
        pay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                payMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                payMouseExited(evt);
            }
        });
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });
        backg3.add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, 130, 40));

        cancelbtm.setBackground(new java.awt.Color(255, 255, 255));
        cancelbtm.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cancelbtm.setText("CANCEL");
        cancelbtm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelbtmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelbtmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelbtmMouseExited(evt);
            }
        });
        cancelbtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtmActionPerformed(evt);
            }
        });
        backg3.add(cancelbtm, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 140, 40));

        bill_id.setBackground(new java.awt.Color(255, 204, 102));
        bill_id.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bill_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        bill_id.setEnabled(false);
        bill_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bill_idActionPerformed(evt);
            }
        });
        backg3.add(bill_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 280, 40));

        amount.setBackground(new java.awt.Color(255, 204, 102));
        amount.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        amount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });
        backg3.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 280, 40));

        title2.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        title2.setText("PAY BILLS FORM");
        backg3.add(title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 260, 60));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Payment Method:");
        backg3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 130, 20));

        type.setBackground(new java.awt.Color(255, 204, 102));
        type.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type of Method", "Gcash", "Cash", "Credit Card" }));
        type.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        backg3.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 280, 40));

        passtxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        passtxt.setText("Bill Type:");
        backg3.add(passtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        Fname1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Fname1.setText("Bill ID:");
        backg3.add(Fname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 110, -1));

        passtxt1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        passtxt1.setText("Amount:");
        backg3.add(passtxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        billtype.setBackground(new java.awt.Color(255, 204, 102));
        billtype.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        billtype.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        billtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billtypeActionPerformed(evt);
            }
        });
        backg3.add(billtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 280, 40));

        passtxt2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        passtxt2.setText("Billing Period:");
        backg3.add(passtxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        billingperiod.setBackground(new java.awt.Color(255, 204, 102));
        billingperiod.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        billingperiod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        billingperiod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billingperiodActionPerformed(evt);
            }
        });
        backg3.add(billingperiod, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 280, 40));

        jPanel2.add(backg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 460, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountActionPerformed

    private void bill_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bill_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bill_idActionPerformed

    private void cancelbtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtmActionPerformed
      
    }//GEN-LAST:event_cancelbtmActionPerformed

    private void cancelbtmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelbtmMouseExited
        cancelbtm.setBackground(white);
    }//GEN-LAST:event_cancelbtmMouseExited

    private void cancelbtmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelbtmMouseEntered
        cancelbtm.setBackground(orange);
    }//GEN-LAST:event_cancelbtmMouseEntered

    private void cancelbtmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelbtmMouseClicked
      payments up = new payments();
        up.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelbtmMouseClicked

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed

    }//GEN-LAST:event_payActionPerformed

    private void payMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payMouseExited
        pay.setBackground(white);
    }//GEN-LAST:event_payMouseExited

    private void payMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payMouseEntered
        pay.setBackground(orange);
    }//GEN-LAST:event_payMouseEntered

    private void payMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payMouseClicked
       dbconn db = new dbconn();

if (bill_id.getText().isEmpty() || amount.getText().isEmpty() || type.getSelectedIndex() == 0) {
    JOptionPane.showMessageDialog(null, "All fields are required", "Warning", JOptionPane.WARNING_MESSAGE);
} else {
    try (Connection con = db.getConnection()) {

    String query = "INSERT INTO tbl_transaction (user_id, bill_id, amount, payment_method, transaction_date, status, billingperiod) " +
               "VALUES (?, ?, ?, ?, ?, ?, ?)";

PreparedStatement pstmt = con.prepareStatement(query);

pstmt.setInt(1, session.getInstance().getId());
pstmt.setInt(2, Integer.parseInt(bill_id.getText()));
pstmt.setDouble(3, Double.parseDouble(amount.getText()));
pstmt.setString(4, type.getSelectedItem().toString());
pstmt.setTimestamp(5, new java.sql.Timestamp(System.currentTimeMillis()));
pstmt.setString(6, "Paid");
pstmt.setString(7, billingperiod.getText()); // <-- Add this line for billing period

        int rowsInserted = pstmt.executeUpdate();

        if (rowsInserted > 0) {
            // Optional: update bill status to "Paid"
            String updateBillQuery = "UPDATE tbl_transaction SET status = 'Paid' WHERE bill_id = ?";
            try (PreparedStatement updateStmt = con.prepareStatement(updateBillQuery)) {
                updateStmt.setInt(1, Integer.parseInt(bill_id.getText()));
                updateStmt.executeUpdate();
            }

            // Log the payment activity
            String logQuery = "INSERT INTO tbl_logs (log_uid, log_action, log_timestamp) VALUES (?, ?, ?)";
            try (PreparedStatement logStmt = con.prepareStatement(logQuery)) {
                logStmt.setInt(1, session.getInstance().getId());
                logStmt.setString(2, "Paid bill with ID: " + bill_id.getText());
                logStmt.setTimestamp(3, new java.sql.Timestamp(System.currentTimeMillis()));
                logStmt.executeUpdate();
            }

            JOptionPane.showMessageDialog(null, "Payment submitted successfully!");
            userDashboard ap = new userDashboard(); // or whatever your JFrame is
            ap.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Failed to submit payment.");
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }
}

    }//GEN-LAST:event_payMouseClicked

    private void billtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billtypeActionPerformed

    private void billingperiodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billingperiodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billingperiodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paybills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paybills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paybills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paybills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paybills().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fname1;
    public javax.swing.JTextField amount;
    private javax.swing.JPanel backg3;
    public javax.swing.JTextField bill_id;
    public javax.swing.JTextField billingperiod;
    public javax.swing.JTextField billtype;
    private javax.swing.JButton cancelbtm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel passtxt;
    private javax.swing.JLabel passtxt1;
    private javax.swing.JLabel passtxt2;
    private javax.swing.JButton pay;
    private javax.swing.JLabel title2;
    public javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
