/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import config.dbconn;
import config.session;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Transaction extends javax.swing.JFrame {

    /**
     * Creates new form Transaction
     */
    public Transaction() {
        initComponents();
        displayUserPayments();
    }
    
    
    public void displayUserPayments() {
    dbconn db = new dbconn();
    try (Connection con = db.getConnection()) {

        String query = "SELECT t.transaction_id, b.bill_name, t.amount, t.payment_method, " +
                       "t.billingperiod, t.transaction_date, t.status " +
                       "FROM tbl_transaction t " +
                       "JOIN bill_type b ON t.bill_id = b.bill_id " +
                       "WHERE t.user_id = ? " +
                       "ORDER BY t.transaction_date DESC";  // no LIMIT, shows all

        PreparedStatement pst = con.prepareStatement(query);
        pst.setInt(1, session.getInstance().getId());
        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{
            "Transaction ID", "Bill Name", "Amount", "Payment Method", "Billing Period", "Date", "Status"
        });

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("transaction_id"),
                rs.getString("bill_name"),
                rs.getDouble("amount"),
                rs.getString("payment_method"),
                rs.getString("billingperiod"),
                rs.getTimestamp("transaction_date"),
                rs.getString("status")
            });
        }

        tbl_transaction.setModel(model);

        rs.close();
        pst.close();

    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error displaying payments!", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

Color orange = new Color(255,102,0);
     Color lightorange = new Color(255,204,102);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        logpanel = new javax.swing.JPanel();
        logtxt = new javax.swing.JLabel();
        Fname1 = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_transaction = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logpanel.setBackground(new java.awt.Color(255, 102, 0));
        logpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logpanelMouseExited(evt);
            }
        });
        logpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logtxt.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        logtxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logtxt.setText("BACK");
        logtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logtxtMouseClicked(evt);
            }
        });
        logpanel.add(logtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, 20));

        jPanel2.add(logpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 140, 40));

        Fname1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Fname1.setText("USER ID");
        jPanel2.add(Fname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 60, -1));

        title2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title2.setText("TRANSACTION");
        jPanel2.add(title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 420, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 870, 110));

        tbl_transaction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TransactionID", "BillName", "Amount", "Payment Methodl", "Billing Period", "Date", "Status"
            }
        ));
        jScrollPane2.setViewportView(tbl_transaction);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 860, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logtxtMouseClicked
       
    }//GEN-LAST:event_logtxtMouseClicked

    private void logpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logpanelMouseClicked
        userDashboard ap = new userDashboard();
        ap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logpanelMouseClicked

    private void logpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logpanelMouseEntered
        logpanel.setBackground(lightorange);
    }//GEN-LAST:event_logpanelMouseEntered

    private void logpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logpanelMouseExited
        logpanel.setBackground(orange);
    }//GEN-LAST:event_logpanelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fname1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel logpanel;
    private javax.swing.JLabel logtxt;
    private javax.swing.JTable tbl_transaction;
    private javax.swing.JLabel title2;
    // End of variables declaration//GEN-END:variables
}
