/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboards;

import config.dbconn;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class addbilltype extends javax.swing.JFrame {

    /**
     * Creates new form addbilltype
     */
    public addbilltype() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        backg3 = new javax.swing.JPanel();
        company = new javax.swing.JTextField();
        lname = new javax.swing.JLabel();
        bill_name = new javax.swing.JTextField();
        description = new javax.swing.JTextField();
        title2 = new javax.swing.JLabel();
        usertxt2 = new javax.swing.JLabel();
        Fname1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        addbil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backg3.setBackground(new java.awt.Color(255, 102, 0));
        backg3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        company.setBackground(new java.awt.Color(255, 204, 102));
        company.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        company.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyActionPerformed(evt);
            }
        });
        backg3.add(company, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 390, 40));

        lname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lname.setText("Company:");
        backg3.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 80, -1));

        bill_name.setBackground(new java.awt.Color(255, 204, 102));
        bill_name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bill_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        bill_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bill_nameActionPerformed(evt);
            }
        });
        backg3.add(bill_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 390, 40));

        description.setBackground(new java.awt.Color(255, 204, 102));
        description.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        description.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionActionPerformed(evt);
            }
        });
        backg3.add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 390, 100));

        title2.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title2.setText("ADD BILL TYPE");
        backg3.add(title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 290, 60));

        usertxt2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        usertxt2.setText("Description:");
        backg3.add(usertxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 100, -1));

        Fname1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Fname1.setText("Bill Name:");
        backg3.add(Fname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 110, -1));

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        backg3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 170, 40));

        addbil.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addbil.setText("ADD BILL");
        addbil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbilMouseClicked(evt);
            }
        });
        backg3.add(addbil, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 170, 40));

        jPanel2.add(backg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 530, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionActionPerformed

    private void bill_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bill_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bill_nameActionPerformed

    private void companyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       billtype bt = new billtype();
       bt.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void addbilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbilMouseClicked
        
      dbconn db = new dbconn();

if (bill_name.getText().isEmpty() || company.getText().isEmpty()) {
    JOptionPane.showMessageDialog(null, "Bill name and company are required.");
} else {
    String query = "INSERT INTO bill_type (bill_name, company, description) VALUES ('"
        + bill_name.getText() + "', '" + company.getText() + "', '" + description.getText() + "')";

    if (db.insertData(query) == 1) {
        JOptionPane.showMessageDialog(this, "Bill type added successfully.");

        // Clear fields after success
       billtype bt = new billtype();
       bt.setVisible(true);
       this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Failed to add bill type.");
    }
}
    }//GEN-LAST:event_addbilMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addbilltype.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addbilltype.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addbilltype.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addbilltype.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addbilltype().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fname1;
    private javax.swing.JButton addbil;
    private javax.swing.JPanel backg3;
    private javax.swing.JTextField bill_name;
    private javax.swing.JTextField company;
    private javax.swing.JTextField description;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lname;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel usertxt2;
    // End of variables declaration//GEN-END:variables
}
