/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboards;
import java.awt.Color;
/**
 *
 * @author Administrator
 */
public class Userinfo extends javax.swing.JFrame {

    /**
     * Creates new form Userinfo
     */
    public Userinfo() {
        initComponents();
    }
     Color orange = new Color(255,102,0);
     Color lightorange = new Color(255,204,102);
     Color white = new Color(255,255,255);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        backg3 = new javax.swing.JPanel();
        enter = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        lname = new javax.swing.JLabel();
        userid = new javax.swing.JTextField();
        Fname = new javax.swing.JLabel();
        nemail = new javax.swing.JTextField();
        title2 = new javax.swing.JLabel();
        usertxt2 = new javax.swing.JLabel();
        usertxt3 = new javax.swing.JLabel();
        nemail1 = new javax.swing.JTextField();
        usertxt4 = new javax.swing.JLabel();
        nemail2 = new javax.swing.JTextField();
        enter1 = new javax.swing.JButton();
        enter2 = new javax.swing.JButton();
        enter3 = new javax.swing.JButton();
        Fname1 = new javax.swing.JLabel();
        userid1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backg3.setBackground(new java.awt.Color(255, 102, 0));
        backg3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enter.setBackground(new java.awt.Color(255, 255, 255));
        enter.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        enter.setText("CHANGE PASSWORD");
        enter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enterMouseExited(evt);
            }
        });
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });
        backg3.add(enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 660, 180, 40));

        email.setBackground(new java.awt.Color(255, 204, 102));
        email.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        backg3.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 280, 40));

        lname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lname.setText("USERNAME");
        backg3.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 130, -1));

        userid.setBackground(new java.awt.Color(255, 204, 102));
        userid.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        userid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        userid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useridActionPerformed(evt);
            }
        });
        backg3.add(userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 280, 40));

        Fname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Fname.setText("NAME");
        backg3.add(Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 130, -1));

        nemail.setBackground(new java.awt.Color(255, 204, 102));
        nemail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nemail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        nemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nemailActionPerformed(evt);
            }
        });
        backg3.add(nemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 280, 40));

        title2.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title2.setText("PERSONAL INFORMATION");
        backg3.add(title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 460, 60));

        usertxt2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        usertxt2.setText(" EMAIL");
        backg3.add(usertxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 120, -1));

        usertxt3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        usertxt3.setText("CONTACT");
        backg3.add(usertxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 120, -1));

        nemail1.setBackground(new java.awt.Color(255, 204, 102));
        nemail1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nemail1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        nemail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nemail1ActionPerformed(evt);
            }
        });
        backg3.add(nemail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 280, 40));

        usertxt4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        usertxt4.setText("PASSWORD");
        backg3.add(usertxt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 590, 120, 20));

        nemail2.setBackground(new java.awt.Color(255, 204, 102));
        nemail2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nemail2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        nemail2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nemail2ActionPerformed(evt);
            }
        });
        backg3.add(nemail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 610, 280, 40));

        enter1.setBackground(new java.awt.Color(255, 255, 255));
        enter1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        enter1.setText("ENTER");
        enter1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enter1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enter1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enter1MouseExited(evt);
            }
        });
        enter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter1ActionPerformed(evt);
            }
        });
        backg3.add(enter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 730, 120, 40));

        enter2.setBackground(new java.awt.Color(255, 255, 255));
        enter2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        enter2.setText("CHANGE EMAIL");
        enter2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enter2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enter2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enter2MouseExited(evt);
            }
        });
        enter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter2ActionPerformed(evt);
            }
        });
        backg3.add(enter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 170, 40));

        enter3.setBackground(new java.awt.Color(255, 255, 255));
        enter3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        enter3.setText("CHANGE CONTACT");
        enter3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enter3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enter3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enter3MouseExited(evt);
            }
        });
        enter3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter3ActionPerformed(evt);
            }
        });
        backg3.add(enter3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 170, 40));

        Fname1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Fname1.setText("USER ID");
        backg3.add(Fname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 60, -1));

        userid1.setBackground(new java.awt.Color(255, 204, 102));
        userid1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        userid1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        userid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userid1ActionPerformed(evt);
            }
        });
        backg3.add(userid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 280, 40));

        jPanel2.add(backg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 600, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterMouseClicked

    }//GEN-LAST:event_enterMouseClicked

    private void enterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterMouseEntered
        enter.setBackground(lightorange);
    }//GEN-LAST:event_enterMouseEntered

    private void enterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterMouseExited
        enter.setBackground(white);
    }//GEN-LAST:event_enterMouseExited

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed

    }//GEN-LAST:event_enterActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void useridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useridActionPerformed

    private void nemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nemailActionPerformed

    private void nemail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nemail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nemail1ActionPerformed

    private void nemail2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nemail2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nemail2ActionPerformed

    private void enter1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_enter1MouseClicked

    private void enter1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_enter1MouseEntered

    private void enter1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_enter1MouseExited

    private void enter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enter1ActionPerformed

    private void enter2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_enter2MouseClicked

    private void enter2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_enter2MouseEntered

    private void enter2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_enter2MouseExited

    private void enter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enter2ActionPerformed

    private void enter3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_enter3MouseClicked

    private void enter3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_enter3MouseEntered

    private void enter3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enter3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_enter3MouseExited

    private void enter3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enter3ActionPerformed

    private void userid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userid1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Userinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Userinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Userinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Userinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Userinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fname;
    private javax.swing.JLabel Fname1;
    private javax.swing.JPanel backg3;
    private javax.swing.JTextField email;
    private javax.swing.JButton enter;
    private javax.swing.JButton enter1;
    private javax.swing.JButton enter2;
    private javax.swing.JButton enter3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lname;
    private javax.swing.JTextField nemail;
    private javax.swing.JTextField nemail1;
    private javax.swing.JTextField nemail2;
    private javax.swing.JLabel title2;
    private javax.swing.JTextField userid;
    private javax.swing.JTextField userid1;
    private javax.swing.JLabel usertxt2;
    private javax.swing.JLabel usertxt3;
    private javax.swing.JLabel usertxt4;
    // End of variables declaration//GEN-END:variables
}
