import java.awt.Color;
import javax.swing.JOptionPane;

public class registrationform extends javax.swing.JFrame {

   
     
    public registrationform() {
        initComponents();
    }
    Color orange = new Color(255,204,102);
    Color lightorange = new Color(245,216,127);
    Color white = new Color(255,255,255);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        title2 = new javax.swing.JLabel();
        usertxt2 = new javax.swing.JLabel();
        userfield2 = new javax.swing.JTextField();
        emailtxt = new javax.swing.JLabel();
        emailfield = new javax.swing.JTextField();
        phonenumtxt = new javax.swing.JLabel();
        phonenumfield = new javax.swing.JTextField();
        passtxt = new javax.swing.JLabel();
        passfield2 = new javax.swing.JPasswordField();
        cpasstxt = new javax.swing.JLabel();
        cpassfield = new javax.swing.JPasswordField();
        backg3 = new javax.swing.JPanel();
        registerbtm4 = new javax.swing.JButton();
        cancelbtm = new javax.swing.JButton();
        lfield = new javax.swing.JTextField();
        lname = new javax.swing.JLabel();
        ffield = new javax.swing.JTextField();
        Fname = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(860, 610));
        setPreferredSize(new java.awt.Dimension(860, 610));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title2.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        title2.setText("REGISTRATION FORM");
        jPanel2.add(title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 350, 60));

        usertxt2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        usertxt2.setText("USERNAME");
        jPanel2.add(usertxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 80, -1));

        userfield2.setBackground(new java.awt.Color(255, 204, 102));
        userfield2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        userfield2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        userfield2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userfield2ActionPerformed(evt);
            }
        });
        jPanel2.add(userfield2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 280, 40));

        emailtxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emailtxt.setText("EMAIL");
        jPanel2.add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 80, -1));

        emailfield.setBackground(new java.awt.Color(255, 204, 102));
        emailfield.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        emailfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        emailfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailfieldActionPerformed(evt);
            }
        });
        jPanel2.add(emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 280, 40));

        phonenumtxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        phonenumtxt.setText("PHONE NUMBER");
        jPanel2.add(phonenumtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 120, -1));

        phonenumfield.setBackground(new java.awt.Color(255, 204, 102));
        phonenumfield.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        phonenumfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        phonenumfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenumfieldActionPerformed(evt);
            }
        });
        jPanel2.add(phonenumfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 280, 40));

        passtxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        passtxt.setText("PASSWORD");
        jPanel2.add(passtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, 80, -1));

        passfield2.setBackground(new java.awt.Color(255, 204, 102));
        passfield2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        passfield2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(passfield2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 280, 40));

        cpasstxt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cpasstxt.setText("CONFIRM PASSWORD");
        jPanel2.add(cpasstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 600, 160, -1));

        cpassfield.setBackground(new java.awt.Color(255, 204, 102));
        cpassfield.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cpassfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(cpassfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 620, 280, 40));

        backg3.setBackground(new java.awt.Color(255, 204, 153));
        backg3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerbtm4.setBackground(new java.awt.Color(255, 255, 255));
        registerbtm4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        registerbtm4.setText("REGISTER NOW");
        registerbtm4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerbtm4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerbtm4MouseExited(evt);
            }
        });
        registerbtm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbtm4ActionPerformed(evt);
            }
        });
        backg3.add(registerbtm4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, 230, 40));

        cancelbtm.setBackground(new java.awt.Color(255, 255, 255));
        cancelbtm.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cancelbtm.setText("CANCEL");
        cancelbtm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelbtmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelbtmMouseExited(evt);
            }
        });
        cancelbtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtmActionPerformed(evt);
            }
        });
        backg3.add(cancelbtm, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 630, 130, 40));

        lfield.setBackground(new java.awt.Color(255, 204, 102));
        lfield.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lfieldActionPerformed(evt);
            }
        });
        backg3.add(lfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 280, 40));

        lname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lname.setText("LASTNAME");
        backg3.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 80, -1));

        ffield.setBackground(new java.awt.Color(255, 204, 102));
        ffield.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ffield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ffield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ffieldActionPerformed(evt);
            }
        });
        backg3.add(ffield, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 280, 40));

        Fname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Fname.setText("FIRST NAME");
        backg3.add(Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 110, -1));

        jPanel2.add(backg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 450, 680));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -20, 1070, 950));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -80, 960, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailfieldActionPerformed

    private void phonenumfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenumfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenumfieldActionPerformed

    private void userfield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userfield2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userfield2ActionPerformed

    private void cancelbtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtmActionPerformed
        userfield2.setText("");
        emailfield.setText("");
        phonenumfield.setText("");
        passfield2.setText("");
        cpassfield.setText("");
        ffield.setText("");
        lfield.setText("");
    }//GEN-LAST:event_cancelbtmActionPerformed

    private void registerbtm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtm4ActionPerformed
                                           
    String username = userfield2.getText();
    String email = emailfield.getText();
    String phoneNumber = phonenumfield.getText();
    String password = passfield2.getText();
    String confirmPassword = cpassfield.getText();
    String firstName = ffield.getText(); // Get first name
    String lastName = lfield.getText();   // Get last name


if (username.isEmpty() || email.isEmpty() || phoneNumber.isEmpty() || password.isEmpty() || confirmPassword.isEmpty() || firstName.isEmpty() || lastName.isEmpty()) {
    JOptionPane.showMessageDialog(this, "All fields are required.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

if (!password.equals(confirmPassword)) {
    JOptionPane.showMessageDialog(this, "Passwords do not match.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

if (!email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
    JOptionPane.showMessageDialog(this, "Invalid email format.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

// Basic name validation (can be improved)
if (!firstName.matches("^[a-zA-Z]+$")) {  // Only letters allowed
    JOptionPane.showMessageDialog(this, "Invalid first name format (letters only).", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

if (!lastName.matches("^[a-zA-Z]+$")) { // Only letters allowed
    JOptionPane.showMessageDialog(this, "Invalid last name format (letters only).", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

    
    }//GEN-LAST:event_registerbtm4ActionPerformed

    private void registerbtm4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerbtm4MouseEntered
            registerbtm4.setBackground(orange);

    }//GEN-LAST:event_registerbtm4MouseEntered

    private void registerbtm4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerbtm4MouseExited
            registerbtm4.setBackground(white);

    }//GEN-LAST:event_registerbtm4MouseExited

    private void cancelbtmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelbtmMouseEntered
            cancelbtm.setBackground(orange);

    }//GEN-LAST:event_cancelbtmMouseEntered

    private void cancelbtmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelbtmMouseExited
            cancelbtm.setBackground(white);
    }//GEN-LAST:event_cancelbtmMouseExited

    private void ffieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ffieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ffieldActionPerformed

    private void lfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrationform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fname;
    private javax.swing.JPanel backg3;
    private javax.swing.JButton cancelbtm;
    private javax.swing.JPasswordField cpassfield;
    private javax.swing.JLabel cpasstxt;
    private javax.swing.JTextField emailfield;
    private javax.swing.JLabel emailtxt;
    private javax.swing.JTextField ffield;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lfield;
    private javax.swing.JLabel lname;
    private javax.swing.JPasswordField passfield2;
    private javax.swing.JLabel passtxt;
    private javax.swing.JTextField phonenumfield;
    private javax.swing.JLabel phonenumtxt;
    private javax.swing.JButton registerbtm4;
    private javax.swing.JLabel title2;
    private javax.swing.JTextField userfield2;
    private javax.swing.JLabel usertxt2;
    // End of variables declaration//GEN-END:variables
}
